name: stakater-comment-on-github-pr-1.0.2
params:
  - name: PR_NUMBER
    value: $(params.prnumber)
  - name: IMAGE
    value: $(params.image_registry_url):$(tasks.stakater-create-git-tag-v2.results.GIT_TAG)
workspaces:
  - name: source
    workspace: source
taskRef: 
  task: stakater-comment-on-github-pr-1.0.2
  kind: ClusterTask
