name: stakater-comment-on-github-pr-v1
params:
  - name: PR_NUMBER
  - name: GIT_REPOSITORY_URL
  - name: IMAGE
    value: $(params.image_registry_url):$(tasks.stakater-create-git-tag-v1.results.GIT_TAG)
workspaces:
  - name: source
    workspace: source
taskRef: 
  task: stakater-comment-on-github-pr-v1
  kind: ClusterTask
