name: stakater-comment-on-github-pr-v2
params:
  - name: pr-number
    value: $(params.prnumber)
  - name: image
    value: $(params.image_registry_url):$(tasks.stakater-create-git-tag-v2.results.GIT_TAG)
workspaces:
  - name: source
    workspace: source
taskRef: 
  task: stakater-comment-on-github-pr-1.0.1
  kind: ClusterTask
