name: stakater-create-environment-v3
taskRef:
  task: stakater-create-environment-v2
  kind: ClusterTask
params:
  - name: REPO_NAME
    value: $(params.repoName)
  - name: PR_NUMBER
    value: $(params.prnumber)
  - name: GIT_URL
    value: $(params.gitrepositoryurl)
  - name: GIT_BRANCH
    value: $(params.gitbranch)
  - name: IMAGE_TAG
    value: $(tasks.stakater-create-git-tag-v2.results.GIT_TAG)
  - name: IMAGE_REPO
    value: $(params.image_registry_url)
workspaces:
  - name: output
    workspace: source
