name: stakater-e2e-test-v1
taskRef:
  task: stakater-e2e-test-v1
  kind: ClusterTask
params:
- name: GIT_ORGANIZATION
  value: github.com/stakater-lab
- name: GIT_E2E_REPO
  value: stakater-nordmart-review-e2e
- name: REPO_NAME
  value: $(params.repoName)
- name: PR_NUMBER
  value: $(params.prnumber)
workspaces:
- name: source
  workspace: source
