name: git-clone
taskRef:
  task: git-clone
  kind: ClusterTask
params:
  - name: revision
    value: $(params.gitrevision)
  - name: depth
    value: "0"
workspaces:
  - name: output
    workspace: source