name: stakater-github-update-cd-repo-v2
taskRef:
  task: stakater-github-update-cd-repo-1.0.8
  kind: ClusterTask
params:
- name: PR_NUMBER
  value: $(params.prnumber)
- name: IMAGE_TAG
  value: $(tasks.stakater-create-git-tag-v2.results.GIT_TAG)
- name: IMAGE_NAME
  value: $(params.image_registry_url)
- name: ENVIRONMENT
  value: $(params.environment)
- name: REPO_PATH
  value: $(params.repoPath)
- name: GIT_REVISION
  value: $(params.gitrevision)
- name: CLUSTER_NAME
  value: $(params.clusterName)
- name: TEAM
  value: $(params.team)
- name: NAMESPACE
  value: $(params.namespace)
- name: HELM_REGISTRY
  value: $(params.helm_registry)
- name: CD_REPO_URL
workspaces:
- name: source
  workspace: source
