name: stakater-helm-push-v2
taskRef:
  task: stakater-helm-push-v1
  kind: ClusterTask
params:
  - name: PR_NUMBER
  - name: REPO_PATH
  - name: GIT_REVISION
  - name: REGISTRY
    value: $(params.helm_registry)
  - name: SEM_VER
    value: $(tasks.stakater-create-git-tag-v2.results.GIT_TAG)
workspaces:
  - name: source
    workspace: source