name: stakater-kube-linting-v1
taskRef:
  task: stakater-kube-linting-v1
  kind: ClusterTask
params:
- name: FILE
  value: manifest.yaml
- name: DEPLOYMENT_FILES_PATH
  value: deploy
workspaces:
- name: source
  workspace: source
