name: stakater-push-main-tag-v1
taskRef:
  task: stakater-push-main-tag-v1
  kind: ClusterTask
params:
  - name: PR_NUMBER
  - name: GIT_REVISION
  - name: IMAGE_TAG
    value: $(tasks.stakater-create-git-tag-v1.results.GIT_TAG)
workspaces:
  - name: source
    workspace: source