taskRef:
  task: stakater-remove-environment-v1
  kind: ClusterTask
name: stakater-remove-environment-v2
when:
- input: $(tasks.stakater-update-cd-repo-v4.status)
  operator: notin
  values: ["Succeeded"]
workspaces:
- name: output
  workspace: source
params:
- name: prNumber
  value: $(params.prnumber)
