name: rox-deployment-check
taskRef:
  task: rox-deployment-check
  kind: ClusterTask
params:
  - name: ROX_API_TOKEN
    value: rhacs-auth-forked
  - name: ROX_CENTRAL_ENDPOINT
    value: rhacs-auth-forked
  - name: FILE
    value: manifest.yaml
  - name: DEPLOYMENT_FILES_PATH
    value: deploy
workspaces:
- name: source
  workspace: source
