name: stakater-sonarqube-scanner-v1
taskRef:
  task: stakater-sonarqube-scanner-v1
  kind: ClusterTask
params:
  - name: sonar_host_url
    value: "http://sonarqube.stakater-sonarqube:9000"
  - name: sonar_project_key
    value: $(params.repoName)
workspaces:
- name: source
  workspace: source
