name: stakater-rox-image-scan-0-0-2
taskRef:
  task: stakater-rox-image-scan-0.0.2
  kind: ClusterTask
params:
  - name: IMAGE
    value: '$(params.image_registry_url):$(tasks.stakater-create-git-tag.results.GIT_TAG)'
  - name: ROX_API_TOKEN
    value: rhacs-auth-forked
  - name: ROX_CENTRAL_ENDPOINT
    value: rhacs-auth-forked
  - name: OUTPUT_FORMAT
    value: csv
  - name: IMAGE_DIGEST
    value: $(tasks.build-and-push.results.IMAGE_DIGEST)
