name: stakater-helm-push-0-0-2
taskRef:
  task: stakater-helm-push-0.0.2
  kind: ClusterTask
params:
  - name: prnumber
  - name: repoPath
  - name: gitrevision
  - name: registry
    value: $(params.helm_registry)
  - name: semVer
    value: $(tasks.stakater-create-git-tag-v2.results.GIT_TAG)
workspaces:
  - name: source
    workspace: source
