name: stakater-rox-deployment-check-0-0-2
taskRef:
  task: stakater-rox-deployment-check-0.0.2
  kind: ClusterTask
params:
  - name: ROX_API_TOKEN
    value: rhacs-auth-forked
  - name: ROX_CENTRAL_ENDPOINT
    value: rhacs-auth-forked
  - name: FILE
    value: manifest.yaml
  - name: DEPLOYMENT_FILES_PATH
    value: deploy
workspaces:
- name: source
  workspace: source
