name: stakater-zap-proxy-v1
params:
  - name: REPO_NAME
    value: $(params.repoName)
  - name: APP_URL
    value: $(params.app_url)
  - name: ALLURE_HOST
    value: $(params.allure_host)
taskRef:
  kind: ClusterTask
  task: stakater-zap-proxy-v1
workspaces:
  - name: source
    workspace: source