name: stakater-rox-image-check-0-0-2
taskRef:
  task: stakater-rox-image-check-0.0.2
  kind: ClusterTask
params:
  - name: IMAGE
    value: '$(params.image_registry_url):$(tasks.stakater-create-git-tag-v2.results.GIT_TAG)'
  - name: ROX_API_TOKEN
    value: rhacs-auth-forked
  - name: ROX_CENTRAL_ENDPOINT
    value: rhacs-auth-forked
  - name: BUILD_IMAGE
	value: $(tasks.stakater-build-image-flag.results.build-image)
