name: stakater-helm-push-0-0-2
taskRef:
  task: stakater-helm-push-0.0.2
  kind: ClusterTask
params:
  - name: PR_NUMBER
  - name: REPO_PATH
  - name: GIT_REVISION
  - name: REGISTRY
    value: $(params.helm_registry)
  - name: SEM_VER
    value: $(tasks.stakater-create-git-tag.results.GIT_TAG)
workspaces:
  - name: source
    workspace: source
