name: stakater-helm-push-0-0-3
taskRef:
  task: stakater-helm-push-0.0.3
  kind: ClusterTask
params:
  - name: PR_NUMBER
    value: $(params.prnumber)
  - name: REPO_PATH
    value: $(params.repoPath)
  - name: GIT_REVISION
    value: $(params.gitrevision)
  - name: REGISTRY
    value: $(params.helm_registry)
  - name: SEM_VER
    value: $(tasks.stakater-create-git-tag.results.GIT_TAG)
workspaces:
  - name: source
    workspace: source
