name: stakater-trivy-scan-0-0-1
taskRef: 
  task: stakater-trivy-scan-0.0.1
  kind: ClusterTask
params:
- name: IMAGE
  value: $(params.image_registry_url):$(tasks.stakater-create-git-tag-v2.results.GIT_TAG)
workspaces:
- name: source
  workspace: source
