name: stakater-checkov-scan-0-0-2
workspaces:
  - name: source
    workspace: source
taskRef: 
  task: stakater-checkov-scan-0.0.2
  kind: ClusterTask
params:
# Must Override in Pipeline
- name: BUILD_IMAGE
  value: $(tasks.stakater-build-image-flag.results.build-image)
