name: stakater-update-cd-repo-v1
params:
  - name: PR_NUMBER
  - name: ENVIRONMENT
  - name: REPO_PATH
  - name: GIT_REVISION
  - name: GIT_ORGANIZATION
  - name: GIT_CD_REPO
  - name: CLUSTER_NAME
  - name: TEAM
  - name: NAMESPACE
  - name: IMAGE_TAG
    value: $(tasks.stakater-create-git-tag-v1.results.GIT_TAG)
  - name: IMAGE_NAME
    value: $(params.image_registry_url)
workspaces:
  - name: source
    workspace: source
taskRef: 
  task: stakater-update-cd-repo-v1
  kind: ClusterTask
  