
name: stakater-main-pr-v1

#Additional Params for pipelines & trigger template
additionalParams:
  - name: repoName
    description: Repository name
    default: "NA"
  - name: prnumberBranch
    description: PR number in case of pr else main
    default: main 

# Pipeline Workspaces
workspaces:
  - name: source
    volumeClaimTemplate:
      accessModes: ReadWriteOnce
      resourcesRequestsStorage: 1Gi
    
pipelines:
  # Pipeline Tasks
  tasks:
    - taskName: git-clone
    - taskName: stakater-create-git-tag-v1
    - taskName: stakater-buildah-v1
    - taskName: stakater-comment-on-github-pr-v1
    - taskName: stakater-helm-push-v1
    - taskName: stakater-update-cd-repo-v1
    - taskName: stakater-push-main-tag-v1

triggertemplate:

  # PipelineRun Name Prefix
  #pipelineRunNamePrefix: $(tt.params.repoName)-$(tt.params.prnumberBranch)
  # Service Account Name 
  serviceAccountName: stakater-tekton-builder
  pipelineRunAnnotations: 
    tekton.dev/git-status: "true"
    tekton.dev/status-context: "pipeline-operator"
    tekton.dev/status-description: "Pipeline running on Openshift"

triggerbinding:
  # All Bindings to be Created are specified here
  bindings:
    # Name
  - name: common-bindings
    bodyParams:
      - name: namespace
        value: ${namespace}
      - name: gitorganization
        value: "github.com/stakater"
      - name: gitcdrepo
        value: "gitops-config-template"
      - name: team
        value: NA
      - name: clusterName
        value: "01-devtest"
      - name: environment
        value: "01-dev"  
      - name: repoName
        value: $(body.repository.name)
      - name: repoPath
        value: $(body.repository.full_name)
      - name: gitrepositoryurl
        value: "https://github.com/$(body.repository.full_name)"
      - name: image_registry_url
        value: "nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/$(body.repository.name)"
      - name: helm_registry
        value: https://nexus-helm-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/repository/helm-charts/
      - name: nexus_url
        value: https://nexus-repository-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/repository/maven-public
      - name: tekton-base-url
        value: https://console-openshift-console.apps.binero-test.8sdzwd1l.kubeapp.cloud/k8s/
      - name: webhook-payload
        value: $(extensions.marshalled-body)
  - name: stakater-main-v1
    # Fields to Extracts from Event Body
    bodyParams:
    - name: gitrevision
      value:  $(body.repository.master_branch)
    - name: prnumberBranch
      value: main
    - name: prnumber
      value: NA        
    - name: author
      value: $(body.head_commit.author.name)

  - name: stakater-pr-v1
    bodyParams:
    - name: gitrevision
      value: $(body.pull_request.head.sha)
    - name: gitbranch
      value: $(body.pull_request.head.ref)
    - name: prnumberBranch
      value: pr-$(body.pull_request.number)
    - name: prnumber
      value: $(body.pull_request.number)  
    - name: author
      value: $(body.pull_request.user.login)

triggers:
  enabled: true
  eventlistenerTriggers:
  - defaultTriggerName: pullrequest
  - defaultTriggerName: push

eventlistener:
  enabled: false
  # Service Account
  serviceAccountName: stakater-tekton-builder
  
  # All Event Triggers
  #triggers:
  #  - pullrequest
  #  - push
  
  #route:
    # Port
    #targetPort: http-listener