
name: stakater-main-pr-v1

pipelines:  
  # Pipeline Workspaces
  workspaces:
    ##- name: source
  # Pipeline Params
  params:
    ##- name: nexus_url
    ##  description: nexus_url
  # Pipeline Tasks
  tasks:
    - taskName: git-clone
    - taskName: stakater-create-git-tag-v1
    - taskName: stakater-buildah-v1
    - taskName: stakater-comment-on-github-pr-v1
    - taskName: stakater-helm-push-v1
    - taskName: stakater-update-cd-repo-v1
    - taskName: stakater-push-main-tag-v1

triggertemplate:
  # Additional Params
  additionalParams:
  - name: repoName
    description: Repository name
    default: "NA"
  - name: prnumberBranch
    description: PR number in case of pr else main
    default: main 
  # PipelineRun Name Prefix
  pipelineRunNamePrefix: $(tt.params.repoName)-$(tt.params.prnumberBranch)
  # Service Account Name 
  serviceAccountName: stakater-tekton-builder
  # Workspace Definition
  workspaces:
    - name: source
      volumeClaimTemplate:
        accessModes: ReadWriteOnce
        resourcesRequestsStorage: 1Gi


triggerbinding:
  # All Bindings to be Created are specified here
  bindings:
    # Name
  - name: stakater-main-v1
    # Fields to Extracts from Event Body
    bodyParams:
     - name: gitrevision
       value:  $(body.repository.master_branch)
     - name: gitorganization
       value: "github.com/stakater"
     - name: gitcdrepo
       value: "gitops-config-template"
     - name: team
       value: NA
     - name: clusterName
       value: "01-devtest"
     - name: environment
       value: "01-dev"
     - name: repoName
       value: $(body.repository.name)
     - name: repoPath
       value: $(body.repository.full_name)
     - name: namespace
       value: ${namespace}
     - name: prnumberBranch
       value: main
     - name: prnumber
       value: NA
     - name: gitrepositoryurl
       value: "https://github.com/$(body.repository.full_name)"
     - name: image_registry_url
       value: "nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/$(body.repository.name)"    
     - name: author
       value: $(body.head_commit.author.name)
     - name: helm_registry
       value: https://nexus-helm-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/repository/helm-charts/
     - name: nexus_url
       value: https://nexus-repository-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/repository/maven-public
     - name: tekton-base-url
       value: https://console-openshift-console.apps.binero-test.8sdzwd1l.kubeapp.cloud/k8s/
     - name: webhook-payload
       value: $(extensions.marshalled-body)

  - name: stakater-pr-v1
    bodyParams:
    - name: gitrevision
      value: $(body.pull_request.head.sha)
    - name: gitbranch
      value: $(body.pull_request.head.ref)
    - name: namespace
      value: ${namespace}              
    - name: gitorganization
      value: "github.com/stakater"
    - name: gitcdrepo
      value: "gitops-config-template"
    - name: team
      value: NA
    - name: clusterName
      value: "01-devtest"
    - name: environment
      value: "01-dev" 
    - name: repoName
      value: $(body.repository.name)
    - name: repoPath
      value: $(body.repository.full_name)
    - name: prnumberBranch
      value: pr-$(body.pull_request.number)
    - name: prnumber
      value: $(body.pull_request.number)
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
    - name: image_registry_url
      value: "nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/$(body.repository.name)" 
    - name: author
      value: $(body.pull_request.user.login)
    - name: helm_registry
      value: https://nexus-helm-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/repository/helm-charts/
    - name: nexus_url
      value: https://nexus-repository-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/repository/maven-public
    - name: tekton-base-url
      value: https://console-openshift-console.apps.binero-test.8sdzwd1l.kubeapp.cloud/k8s/
    - name: webhook-payload
      value: $(extensions.marshalled-body)

eventlistener:
  # Service Account
  serviceAccountName: stakater-tekton-builder
  # All Event Triggers
  triggers:
    - triggerName: pullrequest-merge-trigger
      templateName: stakater-pr-cleaner-v1
      interceptors_cel_filter: "(header.match('X-GitHub-Event', 'pull_request') && body.action == 'closed' )"
      bindings:
      - stakater-pr-cleaner-v1

    - triggerName: pullrequest-trigger
      templateName: stakater-main-pr-v1
      interceptors_cel_filter: "(header.match('X-GitHub-Event', 'pull_request') && body.action == 'opened' || body.action == 'synchronize')"
      bindings:
      - stakater-pr-v1

    - triggerName: push-trigger
      templateName: stakater-main-pr-v1
      interceptors_cel_filter: "(header.match('X-GitHub-Event', 'push') && (body.ref == 'refs/heads/main' || body.ref == 'refs/heads/master') )"
      bindings:
      - stakater-main-v1

route:
  # Labels
  routeLabels: 
    category: route
    router: default

  # Port
  port: http-listener