##########################################################
# Name/Namespace of the application
##########################################################

name: my-helm-chart

##########################################################
# Pipeline Definition
# Creates a Single Trigger Template
##########################################################

pipelines:
  enabled: true
  # Pipeline Workspaces
  workspaces:
    #- name: source
  # Pipeline Params
  params:
    #- name: pipelineparam1
    #  description:
    #- name: pipelineparam2

  # Pipeline Tasks
  tasks:
    # Task Name, Params, Workspaces
    - taskName: 
    #  params:
    #    - name: pipelineparam1
    #    - name: pipelineparam2
    #  workspaces:
    #    - name:  output
    #      workspace: source

    # Task Name, Params, Workspaces
    #- taskName: task2
    #  params:
    #    - name: pipelineparam2
    #  workspaces:
    #    - name:  source
    #      workspace: source
    #  runAfter:
    #  - git-clone


##########################################################
# Trigger Template Definition
# Creates a Single Trigger Template
# Takes Params from pipelines as well as its own params
##########################################################

triggertemplate:

 enabled: true

 # Additional Params
 additionalParams:
 # - name: templateparam
 #   description: templateparam description
 #   default: "templateparam-default"

 # PipelineRun Name Prefix
 pipelineRunNamePrefix: 

 # Service Account Name 
 serviceAccountName: 

 # Workspace Definition
 workspaces:
#  - name: source
#    volumeClaimTemplate:
#      accessModes: ReadWriteOnce
#      resourcesRequestsStorage: 1Gi
#  - name: source1
#    persistentVolumeClaim:
#      claimName: my-pvc
#  - name: source2
#    configMap: 
#      configMapName: my-cm
#  - name: source3
#    emptyDir: "true"

 # Annotations for pipeline run
 pipelineRunAnnotations: 
#  tekton.dev/git-status: "true"
#  tekton.dev/status-context: "pipeline-operator"
#  tekton.dev/status-description: "Pipeline running on Openshift"


##########################################################
# Trigger Binding Definition
# Creates multiple trigger bindings as specified.
# Name and Params needs to be specified for every
##########################################################

triggerbinding:
  enabled: true
  # All Bindings to be Created are specified here
  bindings:
    # Name
  #- name: triggerbinding1
    # Fields to Extracts from Event Body
  #  bodyParams:
  #    - name: param1
  #      value: $(body.param1)

##########################################################
# Event Listener Definition
# 1 or more triggers can be specified
##########################################################

eventlistener:
  enabled: true
  # Service Account
  serviceAccountName: myserviceaccount
  # All Event Triggers
  triggers:
    - templateName: 
#      interceptors_cel_filter: ""
      bindings:
#      - triggerbinding1

##########################################################
# Event Listener Route Definition
##########################################################

route:
  enabled: true

  # Route Labels
  routeLabels: 
    #category: route
    #router: default

  # Port
  port:
    #targetPort: http-listener

  # Wildcard policy
  wildcardPolicy: 

  # tls settings
  tls:
    #termination: edge
    #insecureEdgeTerminationPolicy: Redirect