{{ if .Values.additionalclusterrole.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "stakater-tekton-chart.name" . }}-clusterrole
rules:
  {{- .Values.additionalclusterrole.rules | toYaml |nindent 2}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "stakater-tekton-chart.name" . }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default ( include "stakater-tekton-chart.name" . ) }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "stakater-tekton-chart.name" . }}-clusterrole
{{- end }}