{{- if .Values.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount.name | default (include "stakater-tekton-chart.name" . ) }}
secrets:
  {{- .Values.serviceAccount.secrets | toYaml |nindent 2}}
imagePullSecrets:
  {{- .Values.serviceAccount.imagePullSecrets | toYaml | nindent 2}}
{{- end }}