{{ if .Values.eventlistener.enabled }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "pipeline-charts.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: {{ .Values.serviceAccount.name | default (include "pipeline-charts.name" . ) }}
  {{- if .Values.eventlistener.triggers }}
  triggers:
  {{- if .Values.eventlistener.triggers }}
  {{- range .Values.eventlistener.triggers }}
  {{- if eq .create false }}
  - triggerRef: {{ .name }}
  {{- else }}
  - triggerRef: {{ include "pipeline-charts.name" $ }}-{{ .name }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}