{{ if .Values.eventlistener.enabled }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "pipeline-charts.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: {{ .Values.eventlistener.serviceAccountName }}
  {{- if .Values.triggers }}
  triggers:
  {{- range .Values.triggers.eventlistenerTriggers }}
  {{- if .triggerName }}
  - triggerRef: {{ include "pipeline-charts.name" $ }}-{{ .triggerName }}
  {{- else }}
  - triggerRef: {{ include "pipeline-charts.name" $ }}-{{ .defaultTriggerName }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}