{{ if .Values.eventlistener.enabled }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "pipeline-charts.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.eventlistener.serviceAccountName }}
  serviceAccountName: {{ .Values.eventlistener.serviceAccountName }}
  {{- end }}
  {{- if .Values.eventlistener.triggers }}
  triggers:
  {{- range .Values.eventlistener.triggers }}
  {{- if .templateName }}
  - name: {{ .templateName }}
    {{- if .interceptors_cel_filter }}
    interceptors:
    - cel:
        filter: {{ quote .interceptors_cel_filter }}
    {{- end }}
    {{- if .bindings }}
    bindings:
    {{- range .bindings }}
    - ref: {{ . }}
    {{- end }}
    {{- end }}
    {{- if .templateName }}
    template:
      name: {{ .templateName }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}