{{ if .Values.eventlistener.enabled }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "pipeline-charts.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: {{ .Values.eventlistener.serviceAccountName }}
  {{- if .Values.eventlistener.triggers }}
  triggers:
  {{- range .Values.eventlistener.triggers }}
  {{- if .triggerName }}
  - name: {{ .triggerName }}
    {{- if or .interceptors_cel_filter .interceptors_cel_overlays  }}
    interceptors:
    - cel:
        filter: {{ quote .interceptors_cel_filter }}
        {{- if .interceptors_cel_overlays }}
        overlays:
        {{- toYaml .interceptors_cel_overlays | nindent 12 }}
        {{- end }}
    {{- end }}
    {{- if .bindings }}
    bindings:
    {{- range .bindings }}
    - ref: {{ . }}
    {{- end }}
    {{- end }}
    {{- if .templateName }}
    template:
      name: {{ .templateName }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}