{{ if .Values.eventlistener.enabled }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "pipeline-charts.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{ $sa:= include "pipeline-charts.name" . }}
  serviceAccountName: {{ .Values.eventlistener.serviceAccountName | default $sa }}
  {{- if .Values.eventlistener.triggers }}
  triggers:
  {{- if .Values.eventlistener.triggers }}
  {{- range .Values.eventlistener.triggers }}
  {{- if eq .create false }}
  - triggerRef: {{ .name }}
  {{- else }}
  - triggerRef: {{ include "pipeline-charts.name" $ }}-{{ .name }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}