{{- if .Values.pipelines.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "pipeline-charts.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.pipelines.params }}
  params:
    {{- range $.Values.pipelines.params }}
    {{- if .name }}
    - name: {{ .name }} 
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.pipelines.workspaces }}
  workspaces:
    {{- range $.Values.pipelines.workspaces }}
    - name: {{ .name }} 
    {{- end }}
  {{- end }}
  tasks: 
    {{- range $.Values.pipelines.tasks }}
    - name: {{ .taskName }}
      taskRef:
        - name : {{ .taskName }}
      {{- if .params }}
      params:
        {{- range .params }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value }}
          {{- else }}
          value: $(params.{{.name}})
          {{- end }}    
        {{- end }}
      {{- end }}
      {{- if .workspaces }}
      workspaces:
        {{- range .workspaces }}
        - name: {{ .name }}
          workspace: {{ .workspace }}
        {{- end }}
      {{- end }} 
      {{- if .runAfter }}
      runAfter:
      {{- range .runAfter }}
       - {{ . }}
      {{- end }}
      {{- end }}
    {{- end }}
{{- end }}