{{- if .Values.pipelines.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "pipeline-charts.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- $default_tasks := list }}
  {{- range $path, $_ :=  .Files.Glob  "default-config/tasks/**.yaml" }}
      {{- $task_file := $.Files.Get $path | fromYaml }}
      {{- $default_tasks = append $default_tasks $task_file }}
  {{- end }}
  {{- $pipeline_params := include "pipeline-charts.get_pipeline_params" (list .Values.pipelines.tasks .Values.pipelines.finally $default_tasks ) | fromJson }}
  {{- if $pipeline_params }}
  params:
    {{- range $k,$v := $pipeline_params }}
    - name: {{ $k }}
      type: string
    {{- end }}
  {{- end }}
  {{- if .Values.workspaces }}
  workspaces:
    {{- range $.Values.workspaces }}
    - name: {{ .name }}
    {{- end }}
  {{- end }}
  {{- if .Values.pipelines.finally }}
  finally:
    {{- range .Values.pipelines.finally }}
    {{- $default := include "pipeline-charts.get_default_task_values" (list . $default_tasks ) | fromJson }}
    - name: {{ .taskName | default $default.taskName }}
      {{- if or .when $default.when }}
      when: 
      {{- .when | default $default.when | toYaml | nindent 6 }}
      {{- end }}
      {{- if and .taskSpec .taskName }}
      taskSpec:
        {{- .taskSpec | toYaml | nindent 8 }}
        params:
        {{- range .params }}
        - name: {{ .name }}
        {{- end }}
        workspaces:
        {{- range .workspaces }}
        - name: {{ .name }}
        {{- end }}
      {{- else if and $default.taskSpec .taskName }}
      taskSpec:
        {{- $default.taskSpec | toYaml | nindent 8 }}
        {{- if or $default.params .params }}
        params:
        {{- $addedParams := dict }}
        {{- range .params }}
        {{- $addedParams := set $addedParams .name "e" }}
        - name: {{ .name }}
        {{- end }}
        {{- range $default.params }}
        {{- if hasKey $addedParams .name }}
        {{- else }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if or $default.workspaces .workspaces }}
        workspaces:
          {{- range $default.workspaces }}
          - name: {{ .name }}
            {{- if .workspace }}
            workspace: {{ .workspace }}
            {{- end }}
          {{- end }}
          {{- range .workspaces }}
          - name: {{ .name }}
            workspace: {{ .workspace }}
          {{- end }}
        {{- end }}
      {{- else if .taskRef }}
      taskRef:
          name: {{ .taskRef.name }}
          kind: {{ .taskRef.kind }}
      {{- else }}
      taskRef:
        name: {{ .taskName }}
        kind: ClusterTask
      {{- end }}
      {{- if .taskSpec }}
      {{- if .params }}
      params:
      {{- range .params }}
      - name: {{ .name }}
        {{- if .value }}
        value: {{ .value | quote }}
        {{- else }}
        value: $(params.{{.name}})
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if .workspaces }}
      workspaces:
      {{- range .workspaces }}
      - name: {{ .name }}
        workspace: {{ .workspace }}
      {{- end }}
      {{- end }}
      {{- else }}
      {{- if or $default.params .params }}
      params:
      {{- range $default.params }}
      - name: {{ .name }}
        {{- if .value }}
        value: {{ .value }}
        {{- else }}
        value: $(params.{{.name}})
        {{- end }}
      {{- end }}
      {{- range .params }}
      - name: {{ .name }}
        {{- if .value }}
        value: {{ .value }}
        {{- else }}
        value: $(params.{{.name}})
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if or $default.workspaces .workspaces }}
      workspaces:
        {{- range $default.workspaces }}
        - name: {{ .name }}
          {{- if .workspace }}
          workspace: {{ .workspace }}
          {{- end }}
        {{- end }}
        {{- range .workspaces }}
        - name: {{ .name }}
          workspace: {{ .workspace }}
        {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  tasks:
    {{- $previoustask := "" }}
    {{- range .Values.pipelines.tasks }}
    {{- $default := include "pipeline-charts.get_default_task_values" (list . $default_tasks ) | fromJson }}
    - name: {{ .taskName | default $default.taskName }}
      {{- if or .when $default.when }}
      when: 
      {{- .when | default $default.when | toYaml | nindent 6 }}
      {{- end }}
      {{- if and .taskSpec .taskName }}
      taskSpec:
        {{- .taskSpec | toYaml | nindent 8 }}
        params:
        {{- range .params }}
        - name: {{ .name }}
        {{- end }}
        workspaces:
        {{- range .workspaces }}
        - name: {{ .name }}
        {{- end }}
      {{- else if and $default.taskSpec .taskName }}
      taskSpec:
        {{- $default.taskSpec | toYaml | nindent 8 }}
        {{- if or $default.params .params }}
        params:
        {{- $addedParams := dict }}
        {{- range .params }}
        {{- $addedParams := set $addedParams .name "e" }}
        - name: {{ .name }}
        {{- end }}
        {{- range $default.params }}
        {{- if hasKey $addedParams .name }}
        {{- else }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if or $default.workspaces .workspaces }}
        workspaces:
          {{- range $default.workspaces }}
          - name: {{ .name }}
            {{- if .workspace }}
            workspace: {{ .workspace }}
            {{- end }}
          {{- end }}
          {{- range .workspaces }}
          - name: {{ .name }}
            workspace: {{ .workspace }}
          {{- end }}
        {{- end }}
      {{- else if .taskRef }}
      taskRef:
          name: {{ .taskRef.name }}
          kind: {{ .taskRef.kind }}
      {{- else }}
      taskRef:
        name: {{ .taskName }}
        kind: ClusterTask
      {{- end }}
      {{- if .retries }}
      retries: {{ .retries }}
      {{- end }}
      {{- if .taskSpec }}
      {{- if .params }}
      params:
      {{- range .params }}
      - name: {{ .name }}
        {{- if .value }}
        value: {{ .value | quote }}
        {{- else }}
        value: $(params.{{.name}})
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if .workspaces }}
      workspaces:
      {{- range .workspaces }}
      - name: {{ .name }}
        workspace: {{ .workspace }}
      {{- end }}
      {{- end }}
      {{- else }}
      {{- if or $default.params .params }}
      params:
      {{- $addedParams := dict }}
      {{- range .params }}
      {{- $addedParams := set $addedParams .name "e" }}
      - name: {{ .name }}
        {{- if .value }}
        value: {{ .value | quote }}
        {{- else }}
        value: $(params.{{.name}})
        {{- end }}
      {{- end }}
      {{- range $default.params }}
      {{- if hasKey $addedParams .name }}
      {{- else }}
      - name: {{ .name }}
        {{- if .value }}
        value: {{ .value | quote }}
        {{- else }}
        value: $(params.{{.name}})
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if or $default.workspaces .workspaces }}
      workspaces:
        {{- range $default.workspaces }}
        - name: {{ .name }}
          {{- if .workspace }}
          workspace: {{ .workspace }}
          {{- end }}
        {{- end }}
        {{- range .workspaces }}
        - name: {{ .name }}
          workspace: {{ .workspace }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if or $previoustask .runAfter }}
      runAfter:
        {{- if .runAfter }}
        {{- range .runAfter }}
        - {{ . }}
        {{- end }}
        {{- else }}
        {{- if $previoustask }}
        - {{ $previoustask }}
        {{- end }}
        {{- end -}}
      {{- end }}
      {{- $previoustask = .taskName | default $default.taskName }}
    {{- end }}
{{- end }}
