{{- if .Values.pipelines.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "pipeline-charts.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- $default_tasks := list }}
  {{- range $path, $_ :=  .Files.Glob  "default-config/tasks/**.yaml" }}
      {{- $task_file := $.Files.Get $path | fromYaml }}
      {{- $default_tasks = append $default_tasks $task_file }}
  {{- end }}
  {{- $pipeline_params := include "pipeline-charts.get_pipeline_params" (list .Values.pipelines.tasks .Values.pipelines.finally $default_tasks ) | fromJson }}
  {{- if $pipeline_params }}
  params:
    {{- range $k,$v := $pipeline_params }}
    - name: {{ $k }}
      type: string
    {{- end }}
  {{- end }}
  {{- if .Values.workspaces }}
  workspaces:
    {{- range $.Values.workspaces }}
    - name: {{ .name }}
    {{- end }}
  {{- end }}
  {{- if .Values.pipelines.finally }}
  finally:
    {{- range .Values.pipelines.finally }}
    {{- $default_tasks := include "pipeline-charts.get_default_task_values" (list . $default_tasks ) | fromJson }}
    {{- $task_params := include "pipeline-charts.merge_params" (list $default_tasks.params .params false ) | fromJsonArray }} 
    {{- $task_workspaces := include "pipeline-charts.merge_workspaces" (list $default_tasks.workspaces .workspaces false) | fromJsonArray }} 
    - name: {{ .name | default .defaultTaskName }}
      {{- if or .when $default_tasks.when }}
      when:
      {{- .when | default $default_tasks.when | toYaml | nindent 6 }}
      {{- end }}
      {{- if and .taskSpec .name }}
      taskSpec:
        {{- .taskSpec | toYaml | nindent 8 }}
        {{- if .params }}
        params:
        {{- range .params }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- if .workspaces }}
        workspaces:
        {{- range .workspaces }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
      {{- else if and $default_tasks.taskSpec .defaultTaskName }}
      taskSpec:
        {{- $default_tasks.taskSpec | toYaml | nindent 8 }}
        {{- if $task_params }}
        params:
        {{- range $task_params }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- if $task_workspaces }}
        workspaces:
        {{- range $task_workspaces }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
      {{- else if and .taskRef .name }}
      taskRef:
          name: {{ .taskRef.task }}
          kind: {{ .taskRef.kind | default "ClusterTask" }}
      {{- else if and $default_tasks.taskRef .defaultTaskName }}
      taskRef:
          name: {{ $default_tasks.taskRef.task }}
          kind: {{ $default_tasks.taskRef.kind }}
      {{- end }}
      {{- if .taskSpec }}
      {{- if .params }}
      params:
      {{- range .params }}
      - name: {{ .name }}
        {{- if .value }}
        value: {{ .value | quote }}
        {{- else }}
        value: $(params.{{.name}})
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if .workspaces }}
      workspaces:
      {{- range .workspaces }}
      - name: {{ .name }}
        workspace: {{ .workspace }}
      {{- end }}
      {{- end }}
      {{- else }}
      {{- if $task_params  }}
      params:
      {{- range $task_params }}
      - name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}
      {{- if $task_workspaces  }}
      workspaces:
      {{- range $task_workspaces }}
      - name: {{ .name }}
        workspace: {{ .workspace }}
      {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  tasks:
    {{- $previoustask := "" }}
    {{- range .Values.pipelines.tasks }}
    {{- $default_tasks := include "pipeline-charts.get_default_task_values" (list . $default_tasks ) | fromJson -}}
    {{- $task_params := include "pipeline-charts.merge_params" (list $default_tasks.params .params false ) | fromJsonArray }} 
    {{- $task_workspaces := include "pipeline-charts.merge_workspaces" (list $default_tasks.workspaces .workspaces false) | fromJsonArray }} 
    - name: {{ .name | default .defaultTaskName }}
      {{- if or .when $default_tasks.when }}
      when:
      {{- .when | default $default_tasks.when | toYaml | nindent 6 }}
      {{- end }}
      {{- if and .taskSpec .name }}
      taskSpec:
        {{- .taskSpec | toYaml | nindent 8 }}
        {{- if .params }}
        params:
        {{- range .params }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- if .workspaces }}
        workspaces:
        {{- range .workspaces }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
      {{- else if and $default_tasks.taskSpec .defaultTaskName }}
      taskSpec:
        {{- $default_tasks.taskSpec | toYaml | nindent 8 }}
        {{- if $task_params  }}
        params:
        {{- range $task_params }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- if $task_workspaces }}
        workspaces:
        {{- range $task_workspaces }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
      {{- else if and .taskRef .name }}
      taskRef:
          name: {{ .taskRef.task }}
          kind: {{ .taskRef.kind | default "ClusterTask" }}
      {{- else if and $default_tasks.taskRef .defaultTaskName }}
      taskRef:
          name: {{ $default_tasks.taskRef.task }}
          kind: {{ $default_tasks.taskRef.kind }}
      {{- end }}
      {{- if .retries }}
      retries: {{ .retries }}
      {{- end }}
      {{- if .taskSpec }}
      {{- if .params }}
      params:
      {{- range .params }}
      - name: {{ .name }}
        {{- if .value }}
        value: {{ .value | quote }}
        {{- else }}
        value: $(params.{{.name}})
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if .workspaces }}
      workspaces:
      {{- range .workspaces }}
      - name: {{ .name }}
        workspace: {{ .workspace }}
      {{- end }}
      {{- end }}
      {{- else }}
      {{- if $task_params }}
      params:
      {{- range $task_params }}
      - name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}
      {{- if $task_workspaces  }}
      workspaces:
      {{- range $task_workspaces }}
      - name: {{ .name }}
        workspace: {{ .workspace }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if or $previoustask .runAfter }}
      runAfter:
        {{- if .runAfter }}
        {{- range .runAfter }}
        - {{ . }}
        {{- end }}
        {{- else }}
        {{- if $previoustask }}
        - {{ $previoustask }}
        {{- end }}
        {{- end -}}
      {{- end }}
      {{- $previoustask = (.name | default .defaultTaskName) }}
    {{- end }}
{{- end }}
