kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "pipeline-charts.name" . }}-{{ .Release.Namespace }}
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineresources
      - pipelineruns
    verbs:
      - get
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
      - triggers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - tekton-pipelines-scc
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - deployments
