apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stakater-tekton-builder
subjects:
  - kind: ServiceAccount
    name: stakater-tekton-builder
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: Role
  name: stakater-tekton-builder