{{- if .Values.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "pipeline-charts.name" . }}
secrets:
  {{- .Values.serviceAccount.secrets | toYaml |nindent 2}}
imagePullSecrets:
  {{- .Values.serviceAccount.imagePullSecrets | toYaml | nindent 2}}
{{- end }}