kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "pipeline-charts.name" . }}
secrets:
  - name: nexus-docker-config-forked
  - name: git-auth-forked
imagePullSecrets:
  - name: nexus-docker-config-forked
