kind: ServiceAccount
apiVersion: v1
metadata:
  name: stakater-tekton-builder
secrets:
  - name: nexus-docker-config-forked
  - name: git-auth-forked
imagePullSecrets:
  - name: nexus-docker-config-forked
