{{ if .Values.triggertemplate.enabled }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ include "pipeline-charts.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
    {{- $default_tasks := list }}
    {{- range $path, $_ :=  .Files.Glob  "default-config/tasks/**.yaml" }}
        {{- $task_file := $.Files.Get $path | fromYaml }}
        {{- $default_tasks = append $default_tasks $task_file }}
    {{- end }}
  {{- $default_params := include "pipeline-charts.get_pipeline_params" (list .Values.pipelines.tasks .Values.pipelines.finally $default_tasks ) | fromJson }}
  {{- if $default_params }}
  params:
    {{- range $k,$v := $default_params }}
    - name: {{ $k }}
    {{- end }}
    {{- .Values.triggertemplate.params | toYaml | nindent 4}}
  {{- end }}
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{ .Values.triggertemplate.pipelineRunNamePrefix | default "$(tt.params.repoName)-$(tt.params.prnumberBranch)" }}-
        {{- if .Values.triggertemplate.pipelineRunAnnotations }}
        annotations:
          {{- toYaml .Values.triggertemplate.pipelineRunAnnotations | nindent 10 }}
        {{- end }}
      spec:
        serviceAccountName: {{ .Values.serviceAccount.name | default (include "pipeline-charts.name" . ) }}
        {{- if  $default_params }}
        params:
          {{- range $k,$v := $default_params }}
          - name: {{ $k }}
            value: $(tt.params.{{ $k }})
          {{- end }}
        {{- end }}
        pipelineRef:
          name: {{ include "pipeline-charts.name" . }}
        {{- if .Values.workspaces }}
        workspaces:
          {{- range .Values.workspaces -}}
          {{- if and .volumeClaimTemplate .name }}
          - name: {{ .name }}
            {{- if and .volumeClaimTemplate.accessModes .volumeClaimTemplate.resourcesRequestsStorage }}
            volumeClaimTemplate:
              spec:
                accessModes:
                - {{ .volumeClaimTemplate.accessModes }}
                resources:
                  requests:
                    storage: {{ .volumeClaimTemplate.resourcesRequestsStorage }}
            {{- end -}}
          {{- end -}}
          {{- if and .persistentVolumeClaim .name }}
          - name: {{ .name }}
            {{- if .persistentVolumeClaim.claimName }}
            persistentVolumeClaim:
              claimName: {{ .persistentVolumeClaim.claimName }}
            {{- end -}}
            {{- if .persistentVolumeClaim.subPath }}
            subPath: {{ .persistentVolumeClaim.subPath }}
            {{- end }}
          {{- end }}
          {{- if and .emptyDir .name }}
          - name: {{ .name }}
            emptyDir: {}
          {{- end -}}
          {{- if and .configMap .name }}
          - name: {{ .name }}
            {{- if .configMap.configMapName }}
            configmap:
              name: {{ .configMap.configMapName }}
            {{- end }}
          {{- end }}
          {{- end }}
        {{- end }}
{{- end }}
