{{- range .Values.eventlistener.triggers -}}
{{- if ne .create false }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
    name: {{ include "pipeline-charts.name" $ }}-{{ .name }}
spec:
    {{- $triggers := "default-config/triggers.yaml" | $.Files.Get | fromYaml }}
    {{- $defaultTriggerValues:= include "pipeline-charts.get_event_listener_default_trigger" (list .name $triggers.default_triggers.templates ) | fromJson  -}}
    {{- if or .interceptors $defaultTriggerValues.interceptors }}
    interceptors:
    {{- if .interceptors }}
    {{- toYaml .interceptors | nindent 6 }}
    {{- else }}
    {{- toYaml $defaultTriggerValues.interceptors | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- if or .bindings $defaultTriggerValues.bindings }}
    bindings:
    {{- if .bindings }}
    {{- toYaml .bindings | nindent 6 }}
    {{- else }}
    {{- toYaml $defaultTriggerValues.bindings | nindent 6 }}
    {{- end }}
    {{- end }}
    template: 
        ref: {{ include "pipeline-charts.name" $ }}
{{- end -}}
{{- end -}}
