{{ if .Values.triggertemplate.enabled }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ include "pipeline-charts.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if or .Values.default_pipelines.params .Values.additionalParams }}
  params:
    {{- range .Values.default_pipelines.params }}
    - name: {{ .name }}   
      {{- if .description }}
      description: {{ .description }} 
      {{- end }}
      {{- if .default }}
      default: {{ .default }} 
      {{- end }}
    {{- end }}
    {{- range .Values.additionalParams }}
    - name: {{ .name }}   
      {{- if .description }}
      description: {{ .description }} 
      {{- end }}
      {{- if .default }}
      default: {{ .default }} 
      {{- end }}
    {{- end }}
  {{- end }}
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{ .Values.triggertemplate.pipelineRunNamePrefix | default "$(tt.params.repoName)-$(tt.params.prnumberBranch)" }}-
        namespace: {{ .Release.Namespace }}
        {{- if .Values.triggertemplate.pipelineRunAnnotations }}
        annotations:
          {{- toYaml .Values.triggertemplate.pipelineRunAnnotations | nindent 10 }}
        {{- end }}
      spec:
        {{- if .Values.triggertemplate.serviceAccountName }}
        serviceAccountName: {{ .Values.triggertemplate.serviceAccountName }}
        {{- end }}
        {{- if or .Values.additionalParams .Values.default_pipelines.params }}
        params:
          {{- range .Values.additionalParams }}
          - name: {{ .name }}
            value: $(tt.params.{{.name}})  
          {{- end }}
          {{- range .Values.default_pipelines.params }}
          - name: {{ .name }}
            value: $(tt.params.{{.name}})
          {{- end }}
        {{- end }}
        pipelineRef:
          name: {{ include "pipeline-charts.name" . }}
        {{- if .Values.triggertemplate.workspaces }}
        workspaces:
          {{- range .Values.triggertemplate.workspaces -}}
          {{- if and .volumeClaimTemplate .name }}
          - name: {{ .name }}
            {{- if and .volumeClaimTemplate.accessModes .volumeClaimTemplate.resourcesRequestsStorage }}
            volumeClaimTemplate:
              spec:
                accessModes:
                - {{ .volumeClaimTemplate.accessModes }}
                resources:
                  requests:
                    storage: {{ .volumeClaimTemplate.resourcesRequestsStorage }}
            {{- end -}}
          {{- end -}}
          {{- if and .persistentVolumeClaim .name }}
          - name: {{ .name }}
            {{- if .persistentVolumeClaim.claimName }}
            persistentVolumeClaim:
              claimName: {{ .persistentVolumeClaim.claimName }}
            {{- end -}}
            {{- if .persistentVolumeClaim.subPath }}
            subPath: {{ .persistentVolumeClaim.subPath }}
            {{- end }}
          {{- end }}
          {{- if and .emptyDir .name }}
          - name: {{ .name }}
            emptyDir: {}
          {{- end -}}
          {{- if and .configMap .name }}
          - name: {{ .name }}
            {{- if .configMap.configMapName }}
            configmap:
              name: {{ .configMap.configMapName }}
            {{- end }}
          {{- end }}
          {{- end }}
        {{- end }}
{{- end }}