{{ if .Values.triggerbinding.enabled }}
{{ if .Values.triggerbinding.bindings }}
{{- range .Values.triggerbinding.bindings }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: {{ .name }}
spec:
 params:
 {{- if .bodyParams }}
 {{- range .bodyParams }}
  - name: {{ .name }}
    value: {{ .value}}
 {{- end -}}
 {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}