name: stakater-main-pr-v1
workspaces:
  - name: source
    volumeClaimTemplate:
      accessModes: ReadWriteOnce
      resourcesRequestsStorage: 1Gi
pipelines:
  finally:
  - default_config_task_name: stakater-update-cd-repo-v3
    name: stakater-rollback-cd-repo
    when:
    - input: $(tasks.stakater-e2e-test-v1.status)
      operator: in
      values: [“Failed”]
    params:
    - name: IMAGE_TAG
      value: $(tasks.stakater-create-git-tag-v1.results.CURRENT_GIT_TAG)
  - default_config_task_name: stakater-set-commit-status-v1
    name: set-commit-status-task-result
  - default_config_task_name: stakater-notify-slack-v1
    name: notify-slack
    params:
    - name: namespace
    - name: author
    - name: gitrevision
    - name: repo
      value: $(params.repoName)
    - name: gitrepositoryurl
    - name: tekton-base-url
  tasks:
    - name: git-clone
    - name: stakater-create-git-tag-v1
    - name: stakater-buildah-v1
    - name: stakater-comment-on-github-pr-v1
    - name: stakater-helm-push-v1
    - name: stakater-update-cd-repo-v1
    - name: stakater-push-main-tag-v1
triggertemplate:
  serviceAccountName: stakater-tekton-builder
eventlistener:
  serviceAccountName: stakater-tekton-builder
  triggers:
  - name: stakater-pr-cleaner-v1-pullrequest-merge
    create: false
  - name: pullrequest
    bindings:
    - ref: stakater-pr-v1
  - name: push
    bindings:
    - ref: stakater-main-v1
