name: stakater-maven-main-pr-v1
workspaces:
    - name: source
      volumeClaimTemplate:
          accessModes: ReadWriteOnce
          resourcesRequestsStorage: 1Gi
pipelines:
    tasks:
        - name: git-clone
        - name: stakater-create-git-tag-v1
        - name: maven-settings
          params:
          - name: NEXUS_URL
            value: $(params.nexus_url)
          workspaces:
          - name: source
            workspace: source
        - name: stakater-buildah-v1
        - name: stakater-comment-on-github-pr-v1
        - name: stakater-helm-push-v1
        - name: stakater-update-cd-repo-v1
        - name: stakater-push-main-tag-v1
triggertemplate:
    serviceAccountName: stakater-tekton-builder
eventlistener:
    serviceAccountName: stakater-tekton-builder
    triggers:
    - name: stakater-pr-cleaner-v1-pullrequest-merge
      create: false
    - name: pullrequest
      bindings:
      - ref: stakater-pr-v1
    - name: push
      bindings:
      - ref: stakater-main-v1
