name: stakater-app-sync-and-wait-v1
taskRef: 
  task: stakater-app-sync-and-wait-v1
  kind: ClusterTask
params:
- name: gitrepositoryurl
  value: $(params.gitrepositoryurl)
- name: prNumber
  value: $(params.prnumber)
- name: repoName
  value: $(params.repoName)
- name: timeout
  value: "300"
- name: namespace
  value: $(params.namespace)
- name: IMAGE_TAG
  value: $(tasks.stakater-create-git-tag-v1.results.GIT_TAG)
- name: IMAGE_NAME
  value: $(params.image_registry_url)
workspaces:
- name: source
  workspace: source
