taskName: stakater-app-sync-and-wait-v1
params:
- name: prNumber
  value: $(params.prnumber)
- name: repoName
  value: $(params.repoName)
- name: timeout
  value: "60"
- name: argoAppPrefix
  value: gabbar-dev
- name: IMAGE_TAG
  value: $(tasks.stakater-create-git-tag-v1.results.GIT_TAG)
- name: IMAGE_NAME
  value: $(params.image_registry_url)
