name: stakater-buildah-v1
taskRef: 
  task: stakater-buildah-v1
  kind: ClusterTask
params:
  - name: IMAGE
    value: $(params.image_registry_url):$(tasks.stakater-create-git-tag-v1.results.GIT_TAG)
  - name: TLSVERIFY
    value: "false"
  - name: FORMAT
    value: "docker"
  - name: BUILD_IMAGE
    value: $(tasks.stakater-build-image-flag-v1.results.build-image)
  - name: IMAGE_REGISTRY
    value: $(params.image_registry_url)
  - name: CURRENT_GIT_TAG
    value: $(tasks.stakater-create-git-tag-v1.results.CURRENT_GIT_TAG)
workspaces:
  - name: source
    workspace: source