name: stakater-e2e-test-v1
taskRef:
  task: stakater-e2e-test-v1
  kind: ClusterTask
params:
- name: gitorganization
  value: github.com/stakater-lab
- name: gite2erepo
  value: stakater-nordmart-review-e2e
- name: repoName
  value: $(params.repoName)
- name: prNumber
  value: $(params.prnumber)
workspaces:
- name: source
  workspace: source
