taskName: rox-deployment-check
params:
  - name: rox_api_token
    value: rhacs-auth-forked
  - name: rox_central_endpoint
    value: rhacs-auth-forked
  - name: file
    value: manifest.yaml
  - name: deployment_files_path
    value: deploy
workspaces:
- name: source
  workspace: source
