
name: Push Chart to Helm Repository

on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'

env:
  CHART_NAME: "stakater-tekton-chart"

jobs:
  build:
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - uses: actions/checkout@v3
        name: Checkout Repo
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      # Log in to OC cluster
#      - name: Authenticate to OC cluster
#        uses: redhat-actions/oc-login@v1
#        with:
#          openshift_server_url: ${{ secrets.STAKATER_TEST_CLUSTER }}
#          openshift_username: ${{ secrets.STAKATER_TEST_USER }}
#          openshift_password: ${{ secrets.STAKATER_TEST_PASSWORD }}

      # Generate Tag without tagging the branch
      - name: Generate Tag
        id: generate_tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          DRY_RUN: true

      # Update helm chart version
      - name: Update Chart Version
        env:
          VERSION: ${{ steps.generate_tag.outputs.new_tag }}
        run: |
          make update-chart-version

      # Set Up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      # Set Up Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Set Up ct
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (lint)
        run: ct lint --config ct-config.yml

      # Lint
      - name: Helm Lint
        run: |
          helm lint ${CHART_NAME}

      # Publish helm chart
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          branch: master
          repository: stakater-charts
          target_dir: docs
          token: ${{ secrets.STAKATER_GITHUB_TOKEN }}
          charts_dir: .
          charts_url: https://stakater.github.io/stakater-charts
          owner: stakater
          linting: off
          commit_username: stakater-user
          commit_email: stakater@gmail.com

      # Commit back changes
      - name: Commit files
        run: |
          git config --local user.email "stakater@gmail.com"
          git config --local user.name "stakater-user"
          git status
          git add stakater-tekton-chart/Chart.yaml
          git commit -m "[skip-ci] Update artifacts"

      # Push Changes back
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.STAKATER_GITHUB_TOKEN }}

      # Push tag to repo
      - name: Push Latest Tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      # Notify Slack
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        if: always() # Pick up events even if the job fails or is canceled.
        with:
          status: ${{ job.status }}
          fields: repo,author,action,eventName,ref,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
